// File generated based on the FirebaseConfig from the admin web project (fliqaindiaweb).
// Replace with the actual file generated by: flutterfire configure
// Instructions: https://firebase.google.com/docs/flutter/setup

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for '
          '${defaultTargetPlatform.toString()}. '
          'Please run: flutterfire configure',
        );
    }
  }

  // ── Web ───────────────────────────────────────────────────────────────────
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAiBkjMwM0FyH5gZAA37zkDHTPxqylSHjY',
    appId: '1:484181385774:web:fb56abc8c87ea6945f75bf',
    messagingSenderId: '484181385774',
    projectId: 'fliqaindiaweb',
    authDomain: 'fliqaindiaweb.firebaseapp.com',
    databaseURL: 'https://fliqaindiaweb-default-rtdb.firebaseio.com',
    storageBucket: 'fliqaindiaweb.appspot.com',
    measurementId: 'G-GQQVFY16J5',
  );

  // ── Android ───────────────────────────────────────────────────────────────
  // NOTE: Replace this with your actual Android App ID from Firebase Console.
  // Go to Firebase Console → fliqaindiaweb → Add App → Android
  // Package name: com.fliqaindia.fliqaindia_partner_app
  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAiBkjMwM0FyH5gZAA37zkDHTPxqylSHjY',
    appId: '1:484181385774:android:2247a9dc86dc03b45f75bf', // ← Replace this
    messagingSenderId: '484181385774',
    projectId: 'fliqaindiaweb',
    databaseURL: 'https://fliqaindiaweb-default-rtdb.firebaseio.com',
    storageBucket: 'fliqaindiaweb.appspot.com',
  );

  // ── iOS ───────────────────────────────────────────────────────────────────
  // NOTE: Replace this with your actual iOS App ID from Firebase Console.
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAiBkjMwM0FyH5gZAA37zkDHTPxqylSHjY',
    appId: '1:484181385774:ios:REPLACE_WITH_IOS_APP_ID', // ← Replace this
    messagingSenderId: '484181385774',
    projectId: 'fliqaindiaweb',
    databaseURL: 'https://fliqaindiaweb-default-rtdb.firebaseio.com',
    storageBucket: 'fliqaindiaweb.appspot.com',
    iosClientId:
        'REPLACE_WITH_IOS_CLIENT_ID.apps.googleusercontent.com', // ← Replace this
    iosBundleId: 'com.fliqaindia.fliqaindiaPartnerApp',
  );
}
