// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAiBkjMwM0FyH5gZAA37zkDHTPxqylSHjY',
    appId: '1:484181385774:web:fb56abc8c87ea6945f75bf',
    messagingSenderId: '484181385774',
    projectId: 'fliqaindiaweb',
    authDomain: 'fliqaindiaweb.firebaseapp.com',
    databaseURL: 'https://fliqaindiaweb-default-rtdb.firebaseio.com',
    storageBucket: 'fliqaindiaweb.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAtto5ecws6cBNtQ4bQRC-fN9oBWqMHyh8',
    appId: '1:484181385774:android:4d439cd4a26a01c45f75bf',
    messagingSenderId: '484181385774',
    projectId: 'fliqaindiaweb',
    databaseURL: 'https://fliqaindiaweb-default-rtdb.firebaseio.com',
    storageBucket: 'fliqaindiaweb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA-QSZHrFEXuoLuzFKDHXQ4CGwlunA9YaE',
    appId: '1:484181385774:ios:3058dfd1a3cf0aed5f75bf',
    messagingSenderId: '484181385774',
    projectId: 'fliqaindiaweb',
    databaseURL: 'https://fliqaindiaweb-default-rtdb.firebaseio.com',
    storageBucket: 'fliqaindiaweb.appspot.com',
    iosBundleId: 'com.fliqaindia.fliqaindiaPartnerApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA-QSZHrFEXuoLuzFKDHXQ4CGwlunA9YaE',
    appId: '1:484181385774:ios:3058dfd1a3cf0aed5f75bf',
    messagingSenderId: '484181385774',
    projectId: 'fliqaindiaweb',
    databaseURL: 'https://fliqaindiaweb-default-rtdb.firebaseio.com',
    storageBucket: 'fliqaindiaweb.appspot.com',
    iosBundleId: 'com.fliqaindia.fliqaindiaPartnerApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDm3JRAzpyEINREyZXV2UcrkDXx49q8yG8',
    appId: '1:484181385774:web:a3f78a687cb9a3f15f75bf',
    messagingSenderId: '484181385774',
    projectId: 'fliqaindiaweb',
    authDomain: 'fliqaindiaweb.firebaseapp.com',
    databaseURL: 'https://fliqaindiaweb-default-rtdb.firebaseio.com',
    storageBucket: 'fliqaindiaweb.appspot.com',
  );
}
